//! dnf configuration for immutable image builds (disable kernel protection).

use anyhow::{Context, Result};

use super::{Phase, Transform};

/// Configure dnf so it does not protect the running kernel (there is no
/// running kernel inside the build rootfs) and clears installonlypkgs
/// to avoid kernel-install logic that conflicts with ostree.
#[derive(Debug)]
pub struct DnfConfig;

const DNF4_CONF: &str = "etc/dnf/dnf.conf";
const DNF5_BINARY: &str = "usr/bin/dnf5";
const DNF5_DROPIN_DIR: &str = "etc/dnf/dnf5.conf.d";
const DNF5_DROPIN_FILE: &str = "bootc-base.conf";

impl Transform for DnfConfig {
    fn name(&self) -> &str {
        "dnf_config"
    }

    fn phase(&self) -> Phase {
        Phase::PreChroot
    }

    fn check(&self, ctx: &super::Context) -> Result<bool> {
        let dir = ctx.dir();

        if dir.exists(DNF5_BINARY) {
            let dropin = format!("{DNF5_DROPIN_DIR}/{DNF5_DROPIN_FILE}");
            return Ok(dir.exists(&dropin));
        }

        if !dir.exists(DNF4_CONF) {
            return Ok(false);
        }
        let contents = dir
            .read_to_string(DNF4_CONF)
            .with_context(|| format!("reading {DNF4_CONF}"))?;
        Ok(contents.contains("protect_running_kernel"))
    }

    fn apply(&self, ctx: &super::Context) -> Result<()> {
        let dir = ctx.dir();

        if dir.exists(DNF5_BINARY) {
            // dnf5: write a drop-in config file
            dir.create_dir_all(DNF5_DROPIN_DIR)
                .with_context(|| format!("creating {DNF5_DROPIN_DIR}"))?;
            let dropin_path = format!("{DNF5_DROPIN_DIR}/{DNF5_DROPIN_FILE}");
            dir.write(
                &dropin_path,
                "# Generated by bootc-base-imagectl\n\
                 [main]\n\
                 installonlypkgs=\n\
                 protect_running_kernel=False\n",
            )
            .with_context(|| format!("writing {dropin_path}"))?;
            tracing::debug!("wrote {DNF5_DROPIN_DIR}/{DNF5_DROPIN_FILE}");
        } else {
            // dnf4: append to etc/dnf/dnf.conf
            if let Some(parent) = std::path::Path::new(DNF4_CONF).parent() {
                if !parent.as_os_str().is_empty() {
                    dir.create_dir_all(parent)
                        .with_context(|| format!("creating {}", parent.display()))?;
                }
            }

            let mut contents = if dir.exists(DNF4_CONF) {
                dir.read_to_string(DNF4_CONF)
                    .with_context(|| format!("reading {DNF4_CONF}"))?
            } else {
                "[main]\n".to_string()
            };

            if !contents.contains("installonlypkgs") {
                contents.push_str("installonlypkgs=\n");
            }
            if !contents.contains("protect_running_kernel") {
                contents.push_str("protect_running_kernel=False\n");
            }

            dir.write(DNF4_CONF, &contents)
                .with_context(|| format!("writing {DNF4_CONF}"))?;
            tracing::debug!("wrote {DNF4_CONF}");
        }

        Ok(())
    }
}
