//! Dracut configuration for bootc-compatible initramfs generation.

use anyhow::{Context, Result};

use super::{Phase, Transform};

/// Configure dracut for generic initramfs generation with the modules
/// required by bootc/ostree.
#[derive(Debug)]
pub struct DracutConfig;

const DRACUT_CONF_DIR: &str = "usr/lib/dracut/dracut.conf.d";
const BASE_CONF: &str = "10-bootc-base.conf";
const EXTRA_CONF: &str = "22-bootc-generic.conf";
const ALTFILES_CONF: &str = "59-altfiles.conf";
const TPM2_CONF: &str = "49-bootc-tpm2-tss.conf";

impl Transform for DracutConfig {
    fn name(&self) -> &str {
        "dracut_config"
    }

    fn phase(&self) -> Phase {
        Phase::PreChroot
    }

    fn check(&self, ctx: &super::Context) -> Result<bool> {
        Ok(ctx.dir().exists(format!("{DRACUT_CONF_DIR}/{BASE_CONF}")))
    }

    fn apply(&self, ctx: &super::Context) -> Result<()> {
        let dir = ctx.dir();

        dir.create_dir_all(DRACUT_CONF_DIR)
            .with_context(|| format!("creating {DRACUT_CONF_DIR}"))?;

        // Base dracut configuration
        let base_path = format!("{DRACUT_CONF_DIR}/{BASE_CONF}");
        dir.write(
            &base_path,
            "# Generated by bootc-base-imagectl\n\
             hostonly=no\n\
             export DRACUT_NO_XATTR=1\n\
             add_dracutmodules+=\" kernel-modules dracut-systemd systemd-initrd base ostree bootc \"\n",
        )
        .with_context(|| format!("writing {base_path}"))?;
        tracing::debug!("wrote {DRACUT_CONF_DIR}/{BASE_CONF}");

        // Extra modules from manifest
        let extra_modules = &ctx.manifest.transforms.dracut.extra_modules;
        let modules_str = extra_modules.join(" ");
        let extra_path = format!("{DRACUT_CONF_DIR}/{EXTRA_CONF}");
        dir.write(
            &extra_path,
            format!(
                "# Generated by bootc-base-imagectl\n\
                 add_dracutmodules+=\" {modules_str} \"\n"
            ),
        )
        .with_context(|| format!("writing {extra_path}"))?;
        tracing::debug!("wrote {DRACUT_CONF_DIR}/{EXTRA_CONF}");

        // Altfiles: ensure /usr/lib/passwd and /usr/lib/group are in the initramfs
        let altfiles_path = format!("{DRACUT_CONF_DIR}/{ALTFILES_CONF}");
        dir.write(
            &altfiles_path,
            "# Generated by bootc-base-imagectl\n\
             install_items+=\" /usr/lib/passwd /usr/lib/group \"\n",
        )
        .with_context(|| format!("writing {altfiles_path}"))?;
        tracing::debug!("wrote {DRACUT_CONF_DIR}/{ALTFILES_CONF}");

        // TPM2-TSS dracut module (only if the dracut module is installed)
        if dir.is_dir("usr/lib/dracut/modules.d/97tpm2-tss") {
            let tpm2_path = format!("{DRACUT_CONF_DIR}/{TPM2_CONF}");
            dir.write(
                &tpm2_path,
                "# Generated by bootc-base-imagectl\n\
                 add_dracutmodules+=\" tpm2-tss \"\n",
            )
            .with_context(|| format!("writing {tpm2_path}"))?;
            tracing::debug!("wrote {DRACUT_CONF_DIR}/{TPM2_CONF}");
        } else {
            tracing::debug!("skipping {TPM2_CONF}: dracut module 97tpm2-tss not found");
        }

        Ok(())
    }
}
