//! systemd preset and machine-id configuration for first-boot initialization.

use anyhow::{Context, Result};

use super::{Phase, Transform};

/// Configure systemd: enable tmp.mount, write a preset file for unit
/// enable/disable, and empty /etc/machine-id for first-boot generation.
#[derive(Debug)]
pub struct SystemdConfig;

const TMP_MOUNT_WANTS_DIR: &str = "usr/lib/systemd/system/local-fs.target.wants";
const TMP_MOUNT_TARGET: &str = "../tmp.mount";
const TMP_MOUNT_LINK: &str = "tmp.mount";

const PRESET_DIR: &str = "usr/lib/systemd/system-preset";
const PRESET_FILE: &str = "85-bootc.preset";

const MACHINE_ID: &str = "etc/machine-id";

impl Transform for SystemdConfig {
    fn name(&self) -> &str {
        "systemd_config"
    }

    fn phase(&self) -> Phase {
        Phase::PreChroot
    }

    fn check(&self, ctx: &super::Context) -> Result<bool> {
        let dir = ctx.dir();
        let link_path = format!("{TMP_MOUNT_WANTS_DIR}/{TMP_MOUNT_LINK}");
        let is_symlink = dir
            .symlink_metadata(&link_path)
            .map(|m| m.is_symlink())
            .unwrap_or(false);
        if !is_symlink {
            return Ok(false);
        }

        // Also check machine-id is empty
        if dir.exists(MACHINE_ID) {
            let content = dir
                .read_to_string(MACHINE_ID)
                .with_context(|| format!("reading {MACHINE_ID}"))?;
            if !content.trim().is_empty() {
                return Ok(false);
            }
        }

        Ok(true)
    }

    fn apply(&self, ctx: &super::Context) -> Result<()> {
        let dir = ctx.dir();

        // Enable tmp.mount via symlink
        dir.create_dir_all(TMP_MOUNT_WANTS_DIR)
            .with_context(|| format!("creating {TMP_MOUNT_WANTS_DIR}"))?;

        let link_path = format!("{TMP_MOUNT_WANTS_DIR}/{TMP_MOUNT_LINK}");
        let link_exists = dir.symlink_metadata(&link_path).is_ok();
        if link_exists {
            dir.remove_file(&link_path)
                .with_context(|| format!("removing old {link_path}"))?;
        }
        dir.symlink(TMP_MOUNT_TARGET, &link_path)
            .with_context(|| format!("creating symlink {link_path}"))?;
        tracing::debug!("enabled tmp.mount via symlink");

        // Write systemd preset
        dir.create_dir_all(PRESET_DIR)
            .with_context(|| format!("creating {PRESET_DIR}"))?;

        let mut preset_lines = Vec::new();

        // Disable timers from manifest
        for timer in &ctx.manifest.transforms.systemd.disable_timers {
            preset_lines.push(format!("disable {timer}"));
        }

        // Enable units from manifest
        for unit in &ctx.manifest.transforms.systemd.enable_units {
            preset_lines.push(format!("enable {unit}"));
        }

        let preset_path = format!("{PRESET_DIR}/{PRESET_FILE}");
        let content = format!(
            "# Generated by bootc-base-imagectl\n{}\n",
            preset_lines.join("\n")
        );
        dir.write(&preset_path, &content)
            .with_context(|| format!("writing {preset_path}"))?;
        tracing::debug!("wrote {PRESET_DIR}/{PRESET_FILE}");

        // Empty /etc/machine-id for first-boot generation
        if let Some(parent) = std::path::Path::new(MACHINE_ID).parent() {
            if !parent.as_os_str().is_empty() {
                dir.create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }
        }
        dir.write(MACHINE_ID, "")
            .with_context(|| format!("writing {MACHINE_ID}"))?;
        tracing::debug!("emptied {MACHINE_ID}");

        Ok(())
    }
}
