//! tmpfiles.d generation for /var directory preservation across boots.

use anyhow::{Context, Result};
use cap_std::fs::Dir;
use cap_std_ext::cap_primitives::fs::MetadataExt;
use cap_std_ext::cap_std;

use super::{Phase, Transform, clear_dir};

/// Generate tmpfiles.d entries for /var directories and clean var caches.
///
/// Note: the generic /var -> tmpfiles.d conversion is intended to eventually
/// live in `bootc container lint --fix` (see bootc-dev/bootc#2100 discussion).
/// This implementation serves as a working stopgap until that feature lands.
#[derive(Debug)]
pub struct VarTmpfiles;

const TMPFILES_DIR: &str = "usr/lib/tmpfiles.d";
const TMPFILES_FILENAME: &str = "bootc-base-var.conf";

/// Directories under /var that should always exist (created via tmpfiles.d).
const VAR_STATIC_DIRS: &[(&str, &str)] = &[
    ("var/home", "0755"),
    ("var/roothome", "0700"),
    ("var/lib", "0755"),
    ("var/lib/rpm-state", "0755"),
    ("var/opt", "0755"),
    ("var/srv", "0755"),
    ("var/mnt", "0755"),
    ("var/usrlocal", "0755"),
    ("var/usrlocal/bin", "0755"),
    ("var/usrlocal/etc", "0755"),
    ("var/usrlocal/games", "0755"),
    ("var/usrlocal/include", "0755"),
    ("var/usrlocal/lib", "0755"),
    ("var/usrlocal/lib64", "0755"),
    ("var/usrlocal/sbin", "0755"),
    ("var/usrlocal/share", "0755"),
    ("var/usrlocal/src", "0755"),
    ("var/tmp", "1777"),
];

/// Files to remove from tmpfiles.d (conflict with our symlinks).
const REMOVE_TMPFILES: &[&str] = &["home.conf"];

impl Transform for VarTmpfiles {
    fn name(&self) -> &str {
        "var_tmpfiles"
    }

    fn phase(&self) -> Phase {
        Phase::PreChroot
    }

    fn check(&self, ctx: &super::Context) -> Result<bool> {
        let dir = ctx.dir();
        let conf_path = format!("{TMPFILES_DIR}/{TMPFILES_FILENAME}");
        if !dir.exists(&conf_path) {
            return Ok(false);
        }

        // Check that provision.conf doesn't still reference /root (unmigrated)
        let provision_path = format!("{TMPFILES_DIR}/provision.conf");
        if dir.exists(&provision_path) {
            let content = dir
                .read_to_string(&provision_path)
                .with_context(|| format!("reading {provision_path}"))?;
            for line in content.lines() {
                let trimmed = line.trim();
                if trimmed.is_empty() || trimmed.starts_with('#') {
                    continue;
                }
                let fields: Vec<&str> = trimmed.split_whitespace().collect();
                if fields.len() >= 2 && (fields[1] == "/root" || fields[1].starts_with("/root/")) {
                    return Ok(false);
                }
            }
        }

        Ok(true)
    }

    fn apply(&self, ctx: &super::Context) -> Result<()> {
        let dir = ctx.dir();

        dir.create_dir_all(TMPFILES_DIR)
            .with_context(|| format!("creating {TMPFILES_DIR}"))?;

        // Scan /var for additional directories to preserve
        let mut entries = Vec::new();

        // Static entries first
        for (d, mode) in VAR_STATIC_DIRS {
            entries.push(format!("d /{d} {mode} root root -"));
        }

        // Scan for additional directories created by packages
        if dir.is_dir("var") {
            scan_var_dirs(dir, "var", &mut entries)?;
        }

        entries.sort();
        entries.dedup();

        let conf_path = format!("{TMPFILES_DIR}/{TMPFILES_FILENAME}");
        let content = format!(
            "# Generated by bootc-base-imagectl finalize\n\
             # Ensures /var directories exist on first boot\n\
             {}\n",
            entries.join("\n")
        );
        dir.write(&conf_path, &content)
            .with_context(|| format!("writing {conf_path}"))?;

        // Remove conflicting tmpfiles
        for name in REMOVE_TMPFILES {
            let path = format!("{TMPFILES_DIR}/{name}");
            if dir.exists(&path) {
                dir.remove_file(&path)
                    .with_context(|| format!("removing {path}"))?;
                tracing::debug!("removed conflicting tmpfiles.d/{name}");
            }
        }

        // Clean /var caches (content will be recreated at boot)
        for subdir in ["cache", "tmp", "log"] {
            let path = format!("var/{subdir}");
            if dir.is_dir(&path) {
                clear_dir(dir, &path)?;
            }
        }

        // Ensure var/run -> ../run symlink
        let var_run_is_symlink = dir
            .symlink_metadata("var/run")
            .map(|m| m.is_symlink())
            .unwrap_or(false);
        if dir.exists("var/run") && !var_run_is_symlink {
            dir.remove_dir_all("var/run").context("removing var/run")?;
        }
        if !dir.exists("var/run") && !var_run_is_symlink {
            dir.symlink("../run", "var/run")
                .context("creating var/run -> ../run symlink")?;
        }

        // Fix provision.conf: replace /root paths with /var/roothome using
        // field-aware parsing. tmpfiles.d format is:
        //   type path mode user group age [argument]
        // Only replace when field 1 (the path) equals /root or starts with /root/
        let provision_path = format!("{TMPFILES_DIR}/provision.conf");
        if dir.exists(&provision_path) {
            let content = dir
                .read_to_string(&provision_path)
                .with_context(|| format!("reading {provision_path}"))?;
            let mut seen_roothome = false;
            let fixed_lines: Vec<String> = content
                .lines()
                .filter_map(|line| {
                    let trimmed = line.trim();
                    // Pass through comments and blank lines unchanged
                    if trimmed.is_empty() || trimmed.starts_with('#') {
                        return Some(line.to_string());
                    }
                    let fields: Vec<&str> = trimmed.split_whitespace().collect();
                    if fields.len() >= 2
                        && (fields[1] == "/root" || fields[1].starts_with("/root/"))
                    {
                        let new_path = fields[1].replacen("/root", "/var/roothome", 1);
                        // Deduplicate /var/roothome directory entries
                        if (fields[0] == "d" || fields[0] == "d-") && new_path == "/var/roothome" {
                            if seen_roothome {
                                return None;
                            }
                            seen_roothome = true;
                        }
                        let mut new_fields = fields.clone();
                        new_fields[1] = &new_path;
                        Some(new_fields.join(" "))
                    } else {
                        Some(line.to_string())
                    }
                })
                .collect();
            let final_content = fixed_lines.join("\n") + "\n";
            dir.write(&provision_path, &final_content)
                .with_context(|| format!("writing {provision_path}"))?;
            tracing::debug!("fixed provision.conf: /root -> /var/roothome");
        }

        Ok(())
    }
}

fn scan_var_dirs(dir: &Dir, prefix: &str, entries: &mut Vec<String>) -> Result<()> {
    let sub = match dir.open_dir(prefix) {
        Ok(d) => d,
        Err(e) => {
            tracing::warn!("could not read {prefix}: {e}");
            return Ok(());
        }
    };

    for entry in sub
        .entries()
        .with_context(|| format!("reading entries in {prefix}"))?
    {
        let entry = entry.with_context(|| format!("reading entry in {prefix}"))?;
        let ft = entry
            .file_type()
            .with_context(|| format!("file type in {prefix}"))?;
        if !ft.is_dir() || ft.is_symlink() {
            continue;
        }

        let name = entry.file_name();
        let name = name.to_string_lossy();
        let full = format!("{prefix}/{name}");

        // Skip dirs we handle statically
        if VAR_STATIC_DIRS.iter().any(|(d, _)| *d == full) {
            continue;
        }

        let meta = entry
            .metadata()
            .with_context(|| format!("reading metadata for {full}"))?;
        let mode = format!("{:04o}", meta.mode() & 0o7777);
        entries.push(format!("d /{full} {mode} root root -"));
    }

    Ok(())
}
